# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 홈
    url: /#biography
    weight: 10
  - name: 활동 사진
    url: post
    weight: 20
  - name: 행사
    url: event
    weight: 40
  - name: 포트폴리오
    url: portfolio
    weight: 50
  - parent: Portfolio
    name : Sleighers
    url : /portfolio/sleighers
  - parent: Portfolio
    name : StackGrowth
    url : /portfolio/sg
  - parent: Portfolio
    name : Pintos
    url : /portfolio/pintos
  - name: 찾아오시는 길
    url: contact
    weight: 60
